name: "Run All Tests of YOCKOW's Swift Packages."
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '**/*.swift'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '**/*.swift'
      - '.github/workflows/*.yml'
jobs:
  test:
    defaults:
      run:
        working-directory: '.'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macOS-14
          # - macOS-15
        swift-version:
          - '6.0.1'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ikalnytskyi/action-setup-postgres@v6
      with:
        username: swiftpq_test
        password: swiftpq_test
        database: swiftpq_test
    - name: Install depencencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install zsh libcurl4-openssl-dev libecpg-dev libpgtypes3
    - uses: actions/checkout@v4
    - uses: YOCKOW/Action-setup-swift@main
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: "Execute `run-tests`"
      run: ./run-tests
