name: "Run All Tests of YOCKOW's Swift Packages."
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '**/*.swift'
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/*.yml'
      - 'run-tests'
  pull_request:
    paths:
      - '**/*.swift'
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/*.yml'
jobs:
  test:
    defaults:
      run:
        working-directory: '.'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macOS-26
        swift-version:
          - '6.2'
        swift-compat-ver:
          - '6'
          - '5'
          # - '4.2'
          # - '4'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ikalnytskyi/action-setup-postgres@v7
      with:
        username: swiftpq_test
        password: swiftpq_test
        database: swiftpq_test
    - name: Install depencencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install zsh libcurl4-openssl-dev libecpg-dev libpgtypes3
    - uses: actions/checkout@v4
    - uses: YOCKOW/Action-setup-swift@main
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: "Execute `run-tests`"
      run: ./run-tests --swift-version ${{ matrix.swift-compat-ver }}
